/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RestauranteSoft.c1_Presentacion;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.WindowConstants;

/**
 *
 * @author Marlon
 */
public class FormMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FormMenu() {
        lookandfeel();
        setExtendedState(MAXIMIZED_BOTH);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/iconos/Icono Restaurante.jpg")).getImage());
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/iconos/imagenes/Logo.jpg"));
        JLabel fondo= new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
    }
    
    private void lookandfeel(){
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        ItemGestionarPlatillo = new javax.swing.JMenu();
        gestionarProducto = new javax.swing.JMenuItem();
        gestionarMesa = new javax.swing.JMenuItem();
        gestionarCliente = new javax.swing.JMenuItem();
        gestionarCocinero = new javax.swing.JMenuItem();
        programacionDeMenus = new javax.swing.JMenuItem();
        itemGestionarPedidos = new javax.swing.JMenu();
        registrarPedido = new javax.swing.JMenuItem();
        generarComprobante = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        reporteDeVentas = new javax.swing.JMenuItem();
        reporteDePlatillos = new javax.swing.JMenuItem();
        itemSeguridad = new javax.swing.JMenu();
        gestionarUsuarios = new javax.swing.JMenuItem();
        gestionarPermisos = new javax.swing.JMenuItem();
        itemGestionarSistema = new javax.swing.JMenu();
        ayuda = new javax.swing.JMenuItem();
        acercade = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ItemGestionarPlatillo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Gestionar Programación.jpg"))); // NOI18N
        ItemGestionarPlatillo.setText("Gestionar Programacion");

        gestionarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Gestionar Platillo.jpg"))); // NOI18N
        gestionarProducto.setText("Gestionar Platillo");
        gestionarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarProductoActionPerformed(evt);
            }
        });
        ItemGestionarPlatillo.add(gestionarProducto);

        gestionarMesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Gestionar Mesa.jpg"))); // NOI18N
        gestionarMesa.setText("Gestionar Mesa");
        gestionarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarMesaActionPerformed(evt);
            }
        });
        ItemGestionarPlatillo.add(gestionarMesa);

        gestionarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Gestionar Cliente.jpg"))); // NOI18N
        gestionarCliente.setText("Gestionar Cliente");
        gestionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarClienteActionPerformed(evt);
            }
        });
        ItemGestionarPlatillo.add(gestionarCliente);

        gestionarCocinero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Gestionar Cocinero.jpg"))); // NOI18N
        gestionarCocinero.setText("Gestionar Cocinero");
        gestionarCocinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarCocineroActionPerformed(evt);
            }
        });
        ItemGestionarPlatillo.add(gestionarCocinero);

        programacionDeMenus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Programacion de Menus.jpg"))); // NOI18N
        programacionDeMenus.setText("Programacion de menus");
        programacionDeMenus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programacionDeMenusActionPerformed(evt);
            }
        });
        ItemGestionarPlatillo.add(programacionDeMenus);

        jMenuBar1.add(ItemGestionarPlatillo);

        itemGestionarPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Gestionar Pedidos.jpg"))); // NOI18N
        itemGestionarPedidos.setText("Gestionar Pedidos");

        registrarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Registrar Pedido.jpg"))); // NOI18N
        registrarPedido.setText("Registrar Pedido");
        registrarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarPedidoActionPerformed(evt);
            }
        });
        itemGestionarPedidos.add(registrarPedido);

        generarComprobante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Generar Comprobante.jpg"))); // NOI18N
        generarComprobante.setText("Generar Comprobante");
        generarComprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarComprobanteActionPerformed(evt);
            }
        });
        itemGestionarPedidos.add(generarComprobante);
        itemGestionarPedidos.add(jSeparator3);

        reporteDeVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Reporte de Ventas.jpg"))); // NOI18N
        reporteDeVentas.setText("Reporte de Ventas");
        reporteDeVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteDeVentasActionPerformed(evt);
            }
        });
        itemGestionarPedidos.add(reporteDeVentas);

        reporteDePlatillos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Reporte de Platillos.jpg"))); // NOI18N
        reporteDePlatillos.setText("Reporte de Platillos");
        reporteDePlatillos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteDePlatillosActionPerformed(evt);
            }
        });
        itemGestionarPedidos.add(reporteDePlatillos);

        jMenuBar1.add(itemGestionarPedidos);

        itemSeguridad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Seguridad.jpg"))); // NOI18N
        itemSeguridad.setText("Seguridad");

        gestionarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Gestionar Usuario.jpg"))); // NOI18N
        gestionarUsuarios.setText("Gestionar Usuarios");
        gestionarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarUsuariosActionPerformed(evt);
            }
        });
        itemSeguridad.add(gestionarUsuarios);

        gestionarPermisos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Gestionar Permisos.jpg"))); // NOI18N
        gestionarPermisos.setText("Gestionar Pemisos");
        gestionarPermisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarPermisosActionPerformed(evt);
            }
        });
        itemSeguridad.add(gestionarPermisos);

        jMenuBar1.add(itemSeguridad);

        itemGestionarSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Sistema.jpg"))); // NOI18N
        itemGestionarSistema.setText("Sistema");

        ayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Ayuda.jpg"))); // NOI18N
        ayuda.setText("Ayuda");
        ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaActionPerformed(evt);
            }
        });
        itemGestionarSistema.add(ayuda);

        acercade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Acerca de.jpg"))); // NOI18N
        acercade.setText("Acerca de");
        acercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acercadeActionPerformed(evt);
            }
        });
        itemGestionarSistema.add(acercade);
        itemGestionarSistema.add(jSeparator1);

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Salir.png"))); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        itemGestionarSistema.add(salir);

        jMenuBar1.add(itemGestionarSistema);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gestionarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarProductoActionPerformed
        // TODO add your handling code here:
        FormGestionarPlatillo formGestionarPlatillo= new FormGestionarPlatillo(this, true);
        formGestionarPlatillo.setVisible(true);
    }//GEN-LAST:event_gestionarProductoActionPerformed

    private void gestionarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarMesaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_gestionarMesaActionPerformed

    private void gestionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarClienteActionPerformed
        // TODO add your handling code here:
        FormGestionarCliente formGestionarCliente = new FormGestionarCliente(this, true);
        formGestionarCliente.setVisible(true);
    }//GEN-LAST:event_gestionarClienteActionPerformed

    private void gestionarCocineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarCocineroActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_gestionarCocineroActionPerformed

    private void programacionDeMenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programacionDeMenusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_programacionDeMenusActionPerformed

    private void registrarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarPedidoActionPerformed
        // TODO add your handling code here:
        FormRegistrarPedido formRegistrarPedido= new FormRegistrarPedido(this, true);
        formRegistrarPedido.setVisible(true);
    }//GEN-LAST:event_registrarPedidoActionPerformed

    private void generarComprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarComprobanteActionPerformed
        // TODO add your handling code here:
        FormPedidosPorCobrar formGenerarComprobante= new FormPedidosPorCobrar(this, true);
        formGenerarComprobante.setVisible(true);
    }//GEN-LAST:event_generarComprobanteActionPerformed

    private void reporteDeVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteDeVentasActionPerformed
        // TODO add your handling code here
        FormReporteDeVentas formReporteDeVentas= new FormReporteDeVentas(this, true);
        formReporteDeVentas.setVisible(true);
    }//GEN-LAST:event_reporteDeVentasActionPerformed

    private void reporteDePlatillosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteDePlatillosActionPerformed
        // TODO add your handling code here:
        FormReporteDePlatillos reporteDePlatillos = new FormReporteDePlatillos(this, true);
        reporteDePlatillos.setVisible(true);
    }//GEN-LAST:event_reporteDePlatillosActionPerformed

    private void gestionarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gestionarUsuariosActionPerformed

    private void gestionarPermisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarPermisosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gestionarPermisosActionPerformed

    private void ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ayudaActionPerformed

    private void acercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acercadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acercadeActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here
        int opcionSalida = JOptionPane.showConfirmDialog(this, "¿Desa salir del sistema?","Advertencia",JOptionPane.YES_NO_OPTION);
        if(opcionSalida==JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null, "Gracias por su visita, hasta luego");
            System.exit(0);
        }
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu ItemGestionarPlatillo;
    public javax.swing.JMenuItem acercade;
    public javax.swing.JMenuItem ayuda;
    public javax.swing.JMenuItem generarComprobante;
    public javax.swing.JMenuItem gestionarCliente;
    public javax.swing.JMenuItem gestionarCocinero;
    public javax.swing.JMenuItem gestionarMesa;
    public javax.swing.JMenuItem gestionarPermisos;
    public javax.swing.JMenuItem gestionarProducto;
    public javax.swing.JMenuItem gestionarUsuarios;
    public javax.swing.JMenu itemGestionarPedidos;
    public javax.swing.JMenu itemGestionarSistema;
    public javax.swing.JMenu itemSeguridad;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    public javax.swing.JMenuItem programacionDeMenus;
    public javax.swing.JMenuItem registrarPedido;
    public javax.swing.JMenuItem reporteDePlatillos;
    public javax.swing.JMenuItem reporteDeVentas;
    public javax.swing.JMenuItem salir;
    // End of variables declaration//GEN-END:variables
}
