/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RestauranteSoft.c1_Presentacion;

import RestauranteSoft.c3_dominio.entidades.Cliente;
import RestauranteSoft.c2_aplicacion.GestionarClienteServicio;
import RestauranteSoft.c3_dominio.servicio.ManejadorDeClientes;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Vanessa
 */
public class FormDatosCliente extends javax.swing.JDialog {

    boolean reg;
    /**
     * Creates new form FormRegistrarCliente
     */
    public FormDatosCliente(JDialog owner) {
        super(owner, true);
        initComponents();
        this.setTitle("Registrar Cliente");
        txtDNI.requestFocusInWindow();
        reg=true;
    }

    FormDatosCliente(JDialog owner, Cliente cliente) {
        super(owner, true);
        initComponents();
        this.setTitle("Modificar Cliente");
        txtDNI.setText(cliente.getDni());
        txtNombres.setText(cliente.getNombre());
        txtApellidos.setText(cliente.getApellidos());
        txtDNI.requestFocus();
        reg=false;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        etiApellidos = new javax.swing.JLabel();
        etiDNI = new javax.swing.JLabel();
        etiNombre = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Myriad Pro Light", 1, 24)); // NOI18N
        jLabel1.setText("Registrar Cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        etiApellidos.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        etiApellidos.setText("Apellidos");
        getContentPane().add(etiApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        etiDNI.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        etiDNI.setText("DNI");
        getContentPane().add(etiDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        etiNombre.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        etiNombre.setText("Nombre");
        getContentPane().add(etiNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        txtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidosKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosKeyTyped(evt);
            }
        });
        getContentPane().add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 150, 30));

        txtDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDNIKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDNIKeyTyped(evt);
            }
        });
        getContentPane().add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 150, 30));

        txtNombres.setName("nombre"); // NOI18N
        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombresKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombresKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 150, 30));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String dni, nombre, apellidos;
        if(txtDNI.getText().compareTo("")!=0 && txtNombres.getText().compareTo("")!=0 && txtApellidos.getText().compareTo("")!=0){
            dni = txtDNI.getText();
            nombre = txtNombres.getText();
            apellidos = txtApellidos.getText();
            if(reg){
                try {
                    Cliente cliente = new Cliente(dni, nombre,apellidos);
                    GestionarClienteServicio gestionarClienteServicio = new GestionarClienteServicio();
                    gestionarClienteServicio.guardarCliente(cliente);
                    JOptionPane.showMessageDialog(this,"Se guardo el cliente","Información",JOptionPane.INFORMATION_MESSAGE);
                    limpiarCampos();
                    
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this,e.getMessage()+" Error","No se pudo ingresar el Cliente",JOptionPane.ERROR_MESSAGE);
                }
            }else{
                try {
                    Cliente cliente = new Cliente();
                    GestionarClienteServicio gestionarClienteServicio = new GestionarClienteServicio();
                    gestionarClienteServicio.modificarCliente(cliente);
                    txtDNI.setText(cliente.getDni());
                    txtNombres.setText(cliente.getNombre());
                    txtApellidos.setText(cliente.getApellidos());
                    JOptionPane.showMessageDialog(this,"Se modifico el cliente","Información",JOptionPane.INFORMATION_MESSAGE);
                    limpiarCampos();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this,e.getMessage()+" Error","No se pudo modificar el Cliente",JOptionPane.ERROR_MESSAGE);
                }
            }
        }else
            JOptionPane.showMessageDialog(this, "Faltan llenar datos");
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void txtNombresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNombresKeyReleased

    private void txtNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresKeyTyped

    private void txtDNIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNIKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIKeyReleased

    private void txtDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNIKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIKeyTyped

    private void txtApellidosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosKeyReleased

    private void txtApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosKeyTyped

    private void limpiarCampos(){
        txtDNI.setText("");
        txtNombres.setText("");
        txtApellidos.setText("");
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormDatosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormDatosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormDatosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormDatosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        /java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                FormDatosCliente dialog = new FormDatosCliente(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel etiApellidos;
    private javax.swing.JLabel etiDNI;
    private javax.swing.JLabel etiNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
