/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RestauranteSoft.c1_Presentacion;

import RestauranteSoft.c1_Presentacion.util.ConfiguradorDeTabla;
import RestauranteSoft.c2_aplicacion.GenerarReporteDeVentasServicio;
import RestauranteSoft.c3_dominio.entidades.ComprobanteDePago;
import RestauranteSoft.c3_dominio.servicio.ManejadorComprobanteDePago;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import mastersoft.modelo.ModeloTabla;
import mastersoft.tabladatos.Columna;
import mastersoft.tabladatos.Fila;
import mastersoft.tabladatos.Tabla;

/**
 *
 * @author Sandy
 */
public class FormReporteDeVentas extends javax.swing.JDialog {

    /**
     * Creates new form FrmLogin
     */
    public FormReporteDeVentas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicializarTabla();
        setIconImage(new ImageIcon(getClass().getResource("/iconos/Icono Restaurante.jpg")).getImage());
    }
    
    private void inicializarTabla(){
        Tabla tabla = new Tabla();
        tabla.agregarColumna(new Columna("ID", "java.lang.Integer"));
        tabla.agregarColumna(new Columna("Cliente", "java.lang.String"));
        tabla.agregarColumna(new Columna("Fecha", "java.sql.Date"));
        tabla.agregarColumna(new Columna("Sub Total", "java.lang.String"));                       
        tabla.agregarColumna(new Columna("IGV", "java.lang.String"));
        tabla.agregarColumna(new Columna("Monto Pagado", "java.lang.String"));
        ModeloTabla modeloTabla = new ModeloTabla(tabla);
        tablaVentas.setModel(modeloTabla);        
        ConfiguradorDeTabla.configurarAnchoColumna(tablaVentas, 1, 150, 400, 50);
        ConfiguradorDeTabla.configurarAnchoColumna(tablaVentas, 2, 350, 160, 50);
        ConfiguradorDeTabla.configurarAnchoColumna(tablaVentas, 3, 150, 100, 50);
        ConfiguradorDeTabla.configurarAnchoColumna(tablaVentas, 4, 150, 100, 50);
        ConfiguradorDeTabla.configurarAnchoColumna(tablaVentas, 5, 150, 100, 50);
        ConfiguradorDeTabla.ocultarColumna(tablaVentas, 0);
    }

    private void ReporteVentas(){
        Fila filaTabla;
        double montoTotalSinIGV=0, montoTotalConIGV=0;
        try {
            GenerarReporteDeVentasServicio reporteDeVentasServicio = new GenerarReporteDeVentasServicio();
            ManejadorComprobanteDePago manejadorComprobanteDePago = reporteDeVentasServicio.reporteVentas();
            ModeloTabla modeloTabla = (ModeloTabla)tablaVentas.getModel();
            modeloTabla.eliminarTotalFilas();
            for(ComprobanteDePago venta : manejadorComprobanteDePago.getComprobanteDePago()){
                filaTabla = new Fila();
                filaTabla.agregarValorCelda(venta.getComprobantedepagoid());                
                filaTabla.agregarValorCelda(venta.getCliente().getNombre() + " " + venta.getCliente().getApellidos());
                filaTabla.agregarValorCelda(venta.getFecha());
                filaTabla.agregarValorCelda("S/. "+ String.valueOf(venta.getPedido().getMonto()));                
                filaTabla.agregarValorCelda(venta.getIgv());
                filaTabla.agregarValorCelda("S/. "+ String.valueOf(venta.getMontoAPagar()));
                modeloTabla.agregarFila(filaTabla);
                montoTotalSinIGV+=venta.getPedido().getMonto();
                montoTotalConIGV+= venta.getMontoAPagar();
            }
            modeloTabla.refrescarDatos();
            
            txtMontoTotalSinIGV.setText("S/. "+ montoTotalSinIGV);
            txtMontoTotalConIGV.setText("S/. "+ montoTotalConIGV);
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error"+e.getMessage()+JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();
        btnImprimir = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMontoTotalSinIGV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMontoTotalConIGV = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 0, 24)); // NOI18N
        jLabel6.setText("Reporte De Ventas");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 13, 210, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 58));

        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaVentas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 70, 580, 373));

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Imprimir.png"))); // NOI18N
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, -1, 60));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Cerrar.png"))); // NOI18N
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Monto Total Sin IGV");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtMontoTotalSinIGV.setEditable(false);
        jPanel3.add(txtMontoTotalSinIGV, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 88, -1));

        jLabel2.setText("Monto Total Con IGV");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        txtMontoTotalConIGV.setEditable(false);
        jPanel3.add(txtMontoTotalConIGV, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 85, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 461, 400, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ReporteVentas();
    }//GEN-LAST:event_formWindowOpened

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable tablaVentas;
    private javax.swing.JTextField txtMontoTotalConIGV;
    private javax.swing.JTextField txtMontoTotalSinIGV;
    // End of variables declaration//GEN-END:variables
}
