
package RestauranteSoft.c1_Presentacion;

import RestauranteSoft.c2_aplicacion.GestionarPlatilloServicio;
import RestauranteSoft.c3_dominio.entidades.Cliente;
import RestauranteSoft.c3_dominio.entidades.Platillo;
import RestauranteSoft.c4_persistencia.daoPostgreSql.PlatilloDAOPostgre;
import java.sql.SQLException;
import javax.swing.JDialog;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Karito
 */
public class FormDatosPlatillo extends javax.swing.JDialog {
    
    boolean reg;
    public FormDatosPlatillo(JDialog owner) {
        super(owner, true);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/iconos/Icono Restaurante.jpg")).getImage());
        reg = true;
    }
    
    public FormDatosPlatillo(JDialog owner, Platillo platillo) {
        super(owner, true);
        initComponents();    
        txtDescripcion.setText(platillo.getDescripcion());
        cboTipo.setSelectedItem(platillo.getTipo());
        txtPrecio.setText(String.valueOf(platillo.getPrecio()));
        txtStock.setText(String.valueOf(platillo.getStock()));
        cboEstado.setSelectedItem(platillo.getEstado());
        txtDescripcion.requestFocus();
        reg = false;
    }
    
    public void limpiarCampos(){
        txtDescripcion.setText("");
        cboTipo.setSelectedItem("");
        txtPrecio.setText("");
        txtStock.setText("");
        cboEstado.setSelectedItem("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiDescripcion = new javax.swing.JLabel();
        etiTipo = new javax.swing.JLabel();
        etiPrecio = new javax.swing.JLabel();
        etiStock = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        etiEstado = new javax.swing.JLabel();
        cboTipo = new javax.swing.JComboBox();
        cboEstado = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Producto");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiDescripcion.setText("Descripcion:");
        etiDescripcion.setName("nombre"); // NOI18N
        getContentPane().add(etiDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 67, -1, -1));

        etiTipo.setText("Tipo:");
        etiTipo.setName("dni"); // NOI18N
        getContentPane().add(etiTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 97, -1, -1));

        etiPrecio.setText("Precio:");
        etiPrecio.setName("direccion"); // NOI18N
        getContentPane().add(etiPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 132, -1, -1));

        etiStock.setText("Stock:");
        etiStock.setName("correoe"); // NOI18N
        getContentPane().add(etiStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 162, -1, -1));

        txtDescripcion.setName("nombre"); // NOI18N
        getContentPane().add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 64, 285, -1));

        txtPrecio.setName("direccion"); // NOI18N
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 129, 162, -1));

        txtStock.setName("correoe"); // NOI18N
        getContentPane().add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 159, 162, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Datos del Platillo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 48, 392, 10));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 239, 155, 60));

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 239, 205, 60));

        etiEstado.setText("Estado");
        etiEstado.setName("correoe"); // NOI18N
        getContentPane().add(etiEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 192, -1, -1));

        cboTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Seleccionar>", "MENU", "BEBIDA" }));
        getContentPane().add(cboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 94, 162, -1));

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Seleccionar>", "DISPONIBLE", "NO DISPONIBLE" }));
        getContentPane().add(cboEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 189, 162, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String descripcion = null, tipo, estado;
        double precio;
        int stock;
        if(txtDescripcion.getText().compareTo("")!=0 && cboTipo.getSelectedIndex()!=0 && 
                txtPrecio.getText().compareTo("")!=0 && txtStock.getText().compareTo("")!=0 && 
                cboEstado.getSelectedIndex()!=0){
            descripcion = txtDescripcion.getText();
            tipo = cboTipo.getSelectedItem().toString();
            precio = Double.parseDouble(txtPrecio.getText());
            stock = Integer.parseInt(txtStock.getText());
            estado = cboEstado.getSelectedItem().toString();
            if(reg){
                try {
                    Platillo platillo = new Platillo(descripcion, tipo, stock, precio,estado);
                    GestionarPlatilloServicio gestionarPlatilloServicio = new GestionarPlatilloServicio();
                    gestionarPlatilloServicio.crearPlatillo(platillo);
                    JOptionPane.showMessageDialog(this,"Se guardo el Platillo","Informacion",JOptionPane.INFORMATION_MESSAGE);
                    limpiarCampos();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this,e.getMessage()+" Error","No se pudo ingresar el Platillo",JOptionPane.ERROR_MESSAGE);
                }
            }else{
                try {
                    Platillo platillo = new Platillo(descripcion, tipo, stock, precio,estado);
                    GestionarPlatilloServicio gestionarPlatilloServicio = new GestionarPlatilloServicio();
                    gestionarPlatilloServicio.modificarPlatillo(platillo);
                    JOptionPane.showMessageDialog(this,"Se modificó el Platillo","Informacion",JOptionPane.INFORMATION_MESSAGE);
                    limpiarCampos();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this,e.getMessage()+" Error","No se pudo modificar el Platillo",JOptionPane.ERROR_MESSAGE);
                }   
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        txtDescripcion.requestFocusInWindow();
    }//GEN-LAST:event_formWindowOpened

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cboEstado;
    private javax.swing.JComboBox cboTipo;
    private javax.swing.JLabel etiDescripcion;
    private javax.swing.JLabel etiEstado;
    private javax.swing.JLabel etiPrecio;
    private javax.swing.JLabel etiStock;
    private javax.swing.JLabel etiTipo;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
